test always

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -4,14 +4,25 @@ on:
       - published
 
 jobs:
+  needs:
+    if: ${{ github.event_name != 'pull_request' }}
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "hello"
+
   always:
     if: always()
     runs-on: ubuntu-latest
+    needs: needs
     steps:
-      - name: Debug GitHub Event
+      - name: Finalize
         run: |
-          echo "Event Name: ${{ github.event_name }}"
-          echo "Is Prerelease: ${{ github.event.release.prerelease }}"
+          if [[ "${{ needs.needs.result }}" == "success" || ${{ github.event_name }} != "pull_request" ]]; then
+            echo "All jobs succeeded"
+          else
+            echo "Required jobs failed or were skipped"
+            exit 1
+          fi
 
   on-prerelease:
     if: github.event.release.prerelease
