use new

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -7,4 +7,14 @@ jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - run: echo hello12
+      - name: Simulate random failure
+        run: |
+          echo "Generating a random number..."
+          RANDOM_NUMBER=$(( RANDOM % 2 ))
+          echo "Random number: $RANDOM_NUMBER"
+          if [ $RANDOM_NUMBER -eq 0 ]; then
+            echo "Simulating failure..."
+            exit 1
+          else
+            echo "Simulating success..."
+          fi
